### ISSUE TITLE
xmemory.c incorrectly uses mlock()? Causes CentOS performance problem?

### ISSUE THREAD

**Issue by simonhf** [winlibs/libmcrypt#1]
It seems that mcrypt has its own wrapper for calloc() and calls mlock() with each returned pointer. On regular OSs these extra mlock() calls can make the encryption or decryption operations take up to twice as long. On CentOS then this usage of mlock() can make encryption or decryption operations take 1000s of times longer... seems to be a pathological case, see [1]. The test program at [1] also shows that most malloc() returned pointers cannot be used by mlock(). So should the mlock() used in xmemory.c be deleted?

[1] "mlock() on CentOS is 100 to 520 times slower than the next slowest OS tested. Why?" http://bugs.centos.org/view.php?id=8954

**Comment by weltling** [comment]
Thanks for the info.

Not sure you know, but there was even an RFC suggesting removal of ext/mcrypt from PHP. Since libmcrypt is an unmaintained library. Many projects switch or already have switched to the openssl functionalities.

Thanks.

**Comment by simonhf** [comment]
Yes, thanks. I knew that. However, the good thing about libmcrypt is that it is battle tested and does appear to work well (with the exception of this CentOS performance problem due to the CentOS mlock() implementation). Also, openssl appears to be only slightly better than mcrypt when it comes to support; changes don't happen quickly and I know people who have supplied patches and they never get in etc.

**Comment by cmb69** [comment]
Well, the situation with OpenSLL appears to have improved during the last years, and this repo is meant for libraries on Windows, so I'm closing this ticket.
